apiVersion: v1
kind: Service
metadata:
  name: game-backend-svc
  namespace: game-platform
spec:
  selector:
    app: game-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
