apiVersion: batch/v1
kind: Job
metadata:
  name: game-ingestion-job
  namespace: game-platform
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: game-ingestion
    spec:
      serviceAccountName: game-backend-ksa
      restartPolicy: Never
      containers:
        - name: ingestion
          image: __DOCKERHUB_USERNAME__/game-ingestion:__IMAGE_TAG__
          imagePullPolicy: Always
          env:
            - name: GDP_PROJECT_NAME
              value: cloud-native-game-discovery-platform
            - name: GDP_DB_HOST
              value: game-postgres-svc
            - name: GDP_DB_PORT
              value: "5432"
            - name: GDP_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gdp-db-secret
                  key: POSTGRES_DB
            - name: GDP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: gdp-db-secret
                  key: POSTGRES_USER
            - name: GDP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gdp-db-secret
                  key: POSTGRES_PASSWORD
            - name: GDP_RAWG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gdp-app-secret
                  key: GDP_RAWG_API_KEY
            - name: GDP_INGEST_PAGE_SIZE
              value: "20"
            - name: GDP_GCP_PROJECT_ID
              value: "__GCP_PROJECT_ID__"
            - name: GDP_GCP_LOCATION
              value: "us-central1"
            - name: GDP_EMBEDDING_MODEL
              value: "gemini-embedding-001"
