apiVersion: v1
kind: Service
metadata:
  name: game-postgres-svc
  namespace: game-platform
spec:
  selector:
    app: game-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
